### ISSUE TITLE
ubuntu22.04/kde - file open dialog opens in the background

### ISSUE THREAD

**Issue by cleary** [mindofmatthew/text.management#47]
I assume it's some sort of parent window setting that needs to be passed, but it consistently opens behind the main window

![image](https://user-images.githubusercontent.com/2577966/214140463-9a8e9a62-d276-4c21-b990-8261fb7e93e7.png)

**Comment by mindofmatthew** [comment]
Thanks, this seems to be a general Electron issue. It sounds like VS Code and others are affected as well.

https://github.com/electron/electron/issues/32857

**Comment by Crystal-RainSlide** [comment]
> It sounds like VS Code and others are affected as well.

Someone at VSCodium found that VSCode seems to be not affected:
https://github.com/VSCodium/vscodium/issues/1120#issuecomment-1282565914

And the dialog goes to the background because of the pop up notification:
https://github.com/VSCodium/vscodium/issues/1120#issuecomment-1287551024

And there is a fix-thing by using manual override:
https://github.com/VSCodium/vscodium/issues/1120#issuecomment-1459009363

**Comment by cleary** [comment]
this is not happening in 0.8.0
